# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
stages:
- build
- test

--- 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Run a multi-line script"
        run: |
            echo Add other actions to build,
            echo test, and deploy your project.
      - 
        name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-region: us-east-1
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - 
        id: login-ecr
        name: "Login to Amazon ECR"
        uses: aws-actions/amazon-ecr-login@v1
      - 
        env: 
          ECR_REGISTRY: "${{ steps.login-ecr.outputs.registry }}"
          ECR_REPOSITORY: myprojectdemos
          IMAGE_TAG: "${{ github.sha }}"
        name: "Build, tag, and push image to Amazon ECR"
  test: 
    - 
      name: sonarcloud
      runs-on: ubuntu-latest
      steps: ~
    - 
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - 
      env: 
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
      name: "SonarCloud Scan"
      uses: sonarsource/sonarcloud-github-action@master
